#!/usr/bin/env python3
"""Write a minimal jni.h so the binding can be compile-checked anywhere.

The real build uses the JNI headers shipped with the Android NDK. This stub
exists only so CI (and anyone without an NDK) can still verify that the JNI
layer compiles and actually runs the CLI - it is never shipped.

usage: make_stub_jni.py OUTDIR
"""

import os
import sys

STUB = r'''/* Minimal jni.h - compile-check stub, NOT shipped.
 * Generated by tools/make_stub_jni.py; the real build uses the NDK headers.
 */
#ifndef JNI_STUB_H
#define JNI_STUB_H

#include <stddef.h>
#include <stdint.h>

typedef int jint;
typedef long long jlong;
typedef unsigned char jboolean;
typedef short jshort;
typedef double jdouble;
typedef float jfloat;
typedef int jsize;

typedef void *jobject;
typedef jobject jclass;
typedef jobject jstring;
typedef jobject jthrowable;
typedef jobject jarray;
typedef jarray jobjectArray;
typedef jarray jbooleanArray;
typedef jarray jbyteArray;
typedef jarray jintArray;

/* JNIEnv is a pointer to a table of function pointers, so (*env)->fn(env, ...)
 * resolves exactly as it does against the real header. */
struct JNINativeInterface_ {
    jsize (*GetArrayLength)(void *env, jarray a);
    jobject (*GetObjectArrayElement)(void *env, jobjectArray a, jsize i);
    const char *(*GetStringUTFChars)(void *env, jstring s, void *isCopy);
    void (*ReleaseStringUTFChars)(void *env, jstring s, const char *c);
    void (*DeleteLocalRef)(void *env, jobject o);
    jstring (*NewStringUTF)(void *env, const char *s);
};

typedef struct JNINativeInterface_ *JNIEnv;

#define JNIEXPORT
#define JNICALL
#define JNI_OK 0

#endif /* JNI_STUB_H */
'''


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    outdir = sys.argv[1]
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "jni.h"), "w") as f:
        f.write(STUB)
    print(outdir + "/jni.h")
    return 0


if __name__ == "__main__":
    sys.exit(main())
